POST http://localhost:3001/api/sensors HTTP/1.1
Content-Type: application/json

{
    "name": "Kaupunginkirjasto",
    "address": "Lautakunnankatu 1",
    "city": "Kaarina",
    "location": {
        "type": "Point",
        "coordinates": [22.368027, 60.408285]
    },
    "public": true
}