const mongoose = require('mongoose')
const readingSchema = require('./reading')

/**
 * @openapi
 * Sensor: &sensor
 *   type: object
 *   required:
 *     - name
 *     - sensorType
 *   properties:
 *     id:
 *       type: string
 *       description: the ObjectId generated by MongoDB
 *     name:
 *       type: string
 *       description: name of the sensor
 *     sensorType:
 *       type: string
 *       enum:
 *         - rainFall
 *         - temperature
 *         - pH
 *       description: one of the predefined types for sensors
 *     readings:
 *       type: array
 *       items:
 *         $ref: "#/components/schemas/Reading"
 */
const sensorSchema = new mongoose.Schema({
  name: { 
    type: String, 
    required: true
  },
  sensorType: {
    type: String,
    enum: ['rainFall', 'temperature', 'pH'],
    required: true
  },
  readings: [readingSchema]
})

sensorSchema.index({ name: 1, sensorType: 1 }, { unique: true })

sensorSchema.set('toJSON', {
  transform: (document, returnedObject) => {
    returnedObject.id = returnedObject._id.toString()
    delete returnedObject._id
    delete returnedObject.__v
  }
})

module.exports = mongoose.model('Sensor', sensorSchema)